### ISSUE TITLE
Add author description

### ISSUE THREAD

**Issue by monsij** [ieeesb-nitdgp/insight#9]
![Capture55](https://user-images.githubusercontent.com/23289387/83356313-051c3780-a383-11ea-9324-89bd49e675d3.JPG)

**Location:**  `./config.yml`

**Comment by monsij** [comment]
@arkaseth @PaulSoumik

**Comment by sa-y-an** [comment]
Fixed by 5b060e35aff6581ed395ef54a8c02893da9481f0
